apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dummy-deployment
  template:
    metadata:
      labels:
        k8s-app: dummy-deployment
    spec:
      containers:
      - args:
        - -c
        - java -javaagent:/app1/jmx_prometheus_javaagent-0.2.0.jar=5000:/app1/jmxconfig/config.yaml -jar /app1/spring-boot-web-jsp-1.0.war
        command:
        - bash
        image: prakashsingh08/springboot:v1
        imagePullPolicy: Always
        name: javacontainer
        ports:
        - containerPort: 8080
          name: webport
          protocol: TCP

#      - command:
#        - /bin/sh
#        - -c
#        - ./prometheus-dummy-exporter --metric-name=foo --metric-value=40 --port=8080
#        image: gcr.io/google-samples/prometheus-dummy-exporter:latest
#      - image: docker.io/prakashsingh08/tomcat_with_prom_agent:v1
#        imagePullPolicy: IfNotPresent
#        name: prometheus-dummy-exporter
      - name: prometheus-to-sd
        image: gcr.io/google-containers/prometheus-to-sd:v0.2.3
        command:
        - /monitor
        - --source=:http://localhost:5000
        - --stackdriver-prefix=custom.googleapis.com
        - --pod-id=$(POD_ID)
        - --namespace-id=$(POD_NAMESPACE)
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
